// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1421o6VEoXgaGOkL2wwU4COPsDdJEuR4',
    appId: '1:578330608013:web:b70faff4949800ecb6bdc4',
    messagingSenderId: '578330608013',
    projectId: 'untag-mart',
    authDomain: 'untag-mart.firebaseapp.com',
    storageBucket: 'untag-mart.firebasestorage.app',
    measurementId: 'G-DKCDEJ71P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLShhALlBn0lpzENirSWEQHW_UbGSH0-g',
    appId: '1:578330608013:android:3921cad169c055d6b6bdc4',
    messagingSenderId: '578330608013',
    projectId: 'untag-mart',
    storageBucket: 'untag-mart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCii5-V5Rm3HX-znsg6KrsF-1WBULUh4Js',
    appId: '1:578330608013:ios:9092538c61986ce2b6bdc4',
    messagingSenderId: '578330608013',
    projectId: 'untag-mart',
    storageBucket: 'untag-mart.firebasestorage.app',
    iosBundleId: 'com.example.untagMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCii5-V5Rm3HX-znsg6KrsF-1WBULUh4Js',
    appId: '1:578330608013:ios:9092538c61986ce2b6bdc4',
    messagingSenderId: '578330608013',
    projectId: 'untag-mart',
    storageBucket: 'untag-mart.firebasestorage.app',
    iosBundleId: 'com.example.untagMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1421o6VEoXgaGOkL2wwU4COPsDdJEuR4',
    appId: '1:578330608013:web:06d2c63edf911499b6bdc4',
    messagingSenderId: '578330608013',
    projectId: 'untag-mart',
    authDomain: 'untag-mart.firebaseapp.com',
    storageBucket: 'untag-mart.firebasestorage.app',
    measurementId: 'G-GPPXMBQDFW',
  );
}
